name: Create VM

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-terraform@v1
      with:
        terraform_version: 0.13.5
    - run: terraform init
    - run: terraform apply -auto-approve
