name: Create VM

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-terraform@v1
      with:
        terraform_version: 0.13.5
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: |
        echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$GITHUB_WORKSPACE/key.json"
    - run: terraform init
    - run: terraform apply -auto-approve

